version: '3'
services:
  app:
    build: ./
    #ports:
    #  - 8080:80
    volumes:
      - ./src/:/var/app/src
      - ./resources/:/var/app/resources
    networks:
      #- public
      - internal
    depends_on:
      - mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/var/app/init.sql:ro
    networks:
      - internal
networks:
  #public:
  internal:
